// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

import 'dart:ffi' as ffi;

/// Returns the version string of the native bridge library.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> native_bridge_version();

/// Returns platform info as a null-terminated string.
/// Format: "os|arch|compiler|os_version"
/// e.g. "Linux|x86_64|GCC 12.3.0|6.5.0"
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> get_platform_info();
