// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

import 'dart:ffi' as ffi;

/// Returns the version string of the native bridge library.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> native_bridge_version();

/// Adds two integers.
@ffi.Native<ffi.IntPtr Function(ffi.IntPtr, ffi.IntPtr)>()
external int bridge_sum(int a, int b);

/// Multiplies two integers.
@ffi.Native<ffi.IntPtr Function(ffi.IntPtr, ffi.IntPtr)>()
external int bridge_multiply(int a, int b);

/// A longer lived native function (simulates work).
@ffi.Native<ffi.IntPtr Function(ffi.IntPtr, ffi.IntPtr)>()
external int bridge_sum_long_running(int a, int b);

/// Computes the factorial of n.
@ffi.Native<ffi.IntPtr Function(ffi.IntPtr)>()
external int bridge_factorial(int n);

/// Computes the nth Fibonacci number.
@ffi.Native<ffi.IntPtr Function(ffi.IntPtr)>()
external int bridge_fibonacci(int n);

/// Sums all elements in an intptr_t array.
@ffi.Native<ffi.IntPtr Function(ffi.Pointer<ffi.IntPtr>, ffi.IntPtr)>()
external int bridge_sum_array(ffi.Pointer<ffi.IntPtr> data, int length);

/// Converts a null-terminated UTF-8 string to uppercase in-place.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void bridge_to_upper(ffi.Pointer<ffi.Char> buffer);
